name: React projact artifact
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
        uses: actions/checkout@v3
        - name: Set up Node.js
          uses: actions/setup-node@v3
        - name: Install dependencies
          run: npm install
        - name: Build react app
          run: npm run build

          # Upload build artifacts
        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: react-build
            path: dist