
name: React project artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist
      # Send email notification
      - name: Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.example.com
         server_port: 465
         username: ${{ secrets.MAIL_USERNAME }}
         password: ${{ secrets.MAIL_PASSWORD }}
         subject: React Build Notification
         to: ${{ secrets.RECEIVER_EMAIL }}
         from: ${{ secrets.MAIL_EMAIL }}
         body: build jon of ${{ github.repository }} on branch ${{ github.ref_name }} has completed successfully.
          

        
          